### ISSUE TITLE
Why am I getting "command 'openInGitHub.openProject' not found" error on my VS?

### ISSUE THREAD

**Issue by xsf0105** [antfu/vscode-open-in-github-button#2]
### Describe the bug

![image](https://user-images.githubusercontent.com/14307551/230527156-1c50e15d-eb8f-4b00-a200-54a6c88a1bea.png)

When I run this project locally, I getting command not found error.

May I ask how to solve it?  Thx.

### Reproduction

-

### System Info

```Shell
-
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ntnyq** [comment]
Be sure you have the extension `fabiospampinato.vscode-open-in-github` installed and activitaed.

**Comment by xsf0105** [comment]
@ntnyq  Yeah, you're right. It works. thx
